language: go

go:
  - "1.11.4"

before_script:
  - cd $GOPATH/bin
  - go get -u github.com/gobuffalo/packr/packr
  - cd ${TRAVIS_HOME}/gopath/src/github.com/golangid/goruda
  - export GO111MODULE=on

script:
  - make test
