// GENERATED BY goruda
// This file was generated automatically at
// {{ .TimeStamp }}

package {{.PackageName}}

type {{ .Name }} interface {
	{{ range $key, $val := .Methods }}
		{{ $key | camelcase }}({{ range $index, $element := $val.Attributes }}{{ $element.Name }} {{ $element.Type }}{{ if ne $index $val.Attributes.GetLastIndex }},{{ end }}{{ end }}) ({{ range $index, $element := .ReturnValue }}{{ $element.Type }}{{ if ne $index $val.ReturnValue.GetLastIndex }},{{ end }}{{ end }}, error)
	{{ end }}
}
{{ $receiverName := print .Name "Implementation" }}
type {{ $receiverName }} struct {
}

{{ if gt (len .Methods) 0 }}
{{ range $key, $val := .Methods }}
func (s {{ $receiverName }}) {{ $key | camelcase }}({{ range $index, $element := .Attributes }}{{ $element.Name }} {{ $element.Type }}{{ if ne $index $val.Attributes.GetLastIndex }},{{ end }}{{ end }}) ({{ range $index, $element := .ReturnValue }}{{ $element.Type }}{{ if ne $index $val.ReturnValue.GetLastIndex }},{{ end }}{{ end }}, error) {
	 return {{ range $index, $element := .ReturnValue }}{{ $element.Type }}{{ if ne $index $val.ReturnValue.GetLastIndex }},{{ end }}{{ end }}{}, nil
}
{{ end }}
{{ end }}
