openapi: "3.0.0"
info:
  version: 1.0.0
  title: Menekel
  license:
    name: MIT
servers:
  - url: http://menekel.swagger.io/v1
paths:
  /article:
    get:
      summary: List all article
      operationId: listArticles
      tags:
        - articles
      parameters:
        - name: num
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
        - name: cursor
          in: query
          description: next cursor for pagination
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A paged array of articles
          headers:
            x-cursor:
              description: A cursor to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Articles"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create an article
      operationId: createArticles
      tags:
        - articles
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Article"
      responses:
        '201':
          description: Created Article response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /article/{articleId}:
    put:
      summary: Update an article
      operationId: updateArticle
      tags:
        - article
      parameters:
        - name: articleId
          in: path
          required: true
          description: The id of the article to update
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Article"
      responses:
        '200':
          description: Updated Article response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete certain article by ID
      operationId: deleteArticleById
      tags:
        - article
      parameters:
        - name: articleId
          in: path
          required: true
          description: The id of the article to delete
          schema:
            type: string
      responses:
        '204':
          description: Expected response when deleting article is success
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      summary: Info for a specific article
      operationId: showArticleById
      tags:
        - articles
      parameters:
        - name: articleId
          in: path
          required: true
          description: The id of the article to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Article:
      required:
        - id
        - title
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        title:
          type: string
        tag:
          $ref: "#/components/schemas/Tag"
        author:
          $ref: "#/components/schemas/Author"
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date
        details:
          oneOf:
            - $ref: '#/components/schemas/Tag'
            - $ref: '#/components/schemas/Topic'
        publisher:
          type: object
          properties:
            id:
              type: string
            name:
              type: string 

    Tag:
        properties:
          type:
            type: string
          content:
            oneOf:
              - type: string
              - $ref: "#/components/schemas/Topic"
    Topic:
        properties:
          id:
            type: string
          name: 
            type: string
    Author:
      properties:
        id:
          type: string
        name:
          type: string 
    Articles:
      type: array
      items:
        $ref: "#/components/schemas/Article"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string